# Generated by Django 3.2.24 on 2024-03-28 10:01

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='../default_profile_gfyvrr', force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[300, 300], upload_to='images/'),
        ),
    ]
