# Generated by Django 3.2.24 on 2024-03-28 10:01

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_image_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='../default_post_mpxuln', force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[300, 300], upload_to='images/'),
        ),
    ]
